### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by williamlapa** [streamlit/example-app-commenting#3]
During run streamlit, this issue happens, how can I solve?

ImportError: cannot import name 'chart' from 'utils' 
(D:\ANACONDA\envs\conda_streamlit\lib\site-packages\utils\__init__.py)

**Comment by blackary** [comment]
Did you clone the whole repository, or just the `streamlit_app.py` file? You'll need to also copy the files in the `utils` folder for it to work properly.

**Comment by randyzwitch** [comment]
@blackary This could also be a situation where people inside streamlit tend to do `streamlit run directory/file.py` and users do `streamlit run file.py` and the relative imports are different

**Comment by blackary** [comment]
True. In this case, if you clone the whole repository, and do `streamlit run streamlit_app.py`, it should be able to import `chart` from the `utils` module without any issue.
